### ISSUE TITLE
Cannot upload resulting file

### ISSUE THREAD

**Issue by brian000** [Djings/slacksd#1]
I have this bot working great except for the part at the end when it goes to upload the output image that stable-diffusion generates.  It successfully catches the command out of the channel, forks off a run of sd, and then at the end it errors out saying that there's no such file/dir.

For the record, I'm on commit f4d013a.

```
DEBUG:slack_sdk.web.base_client:Sending a request - url: https://www.slack.com/api/files.upload, query_params: {}, body_params: {'channels': 'XXXXXX,XXXXXX', 'filename': '000017.3587450021.png', 'title': 'test test test -s1 -W512 -H512 -C7.5 -Ak_lms -S3587450021'}, files: {'file': '[1] /Users/brian/src/sd-slack/sdbotoutput/000017.3587450021.png'}, json_body: None, headers: {'Authorization': '(redacted)', 'User-Agent': 'Python/3.10.6 slackclient/3.18.3 Darwin/21.6.0'}
ERROR:slack_sdk.socket_mode.builtin.client:Failed to run a message listener: [Errno 2] No such file or directory: b'[1] /Users/brian/src/sd-slack/sdbotoutput/000017.3587450021.png'
Traceback (most recent call last):
  File "/Users/brian/src/sd-slack/lib/python3.10/site-packages/slack_sdk/socket_mode/client.py", line 134, in run_message_listeners
    listener(self, message, raw_message)  # type: ignore
  File "/Users/brian/src/sd-slack/socket_bot.py", line 285, in process_slack_reply
    result = client.web_client.files_upload(
  File "/Users/brian/src/sd-slack/lib/python3.10/site-packages/slack_sdk/web/client.py", line 2979, in files_upload
    return self.api_call("files.upload", files={"file": file}, data=kwargs)
  File "/Users/brian/src/sd-slack/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/Users/brian/src/sd-slack/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
  File "/Users/brian/src/sd-slack/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 269, in _urllib_api_call
    f: BinaryIO = open(v.encode("utf-8", "ignore"), "rb")
FileNotFoundError: [Errno 2] No such file or directory: b'[1] /Users/brian/src/sd-slack/sdbotoutput/000017.3587450021.png'
DEBUG:slack_sdk.socket_mode.builtin.client:Message processing completed (type: None, envelope_id: None)
```

However, that file definitely exists: and is not empty.
```
% ll /Users/brian/src/sd-slack/sdbotoutput/000017.3587450021.png
-rw-r--r--  1 brian  staff   376K Sep 13 14:58 /Users/brian/src/sd-slack/sdbotoutput/000017.3587450021.png

% file /Users/brian/src/sd-slack/sdbotoutput/000017.3587450021.png
/Users/brian/src/sd-slack/sdbotoutput/000017.3587450021.png: PNG image data, 512 x 512, 8-bit/color RGB, non-interlaced
```

On the Slack side, I have given the bot all the necessary scopes, including files:write.

Any suggestions?

**Comment by Djings** [comment]
The parsed filename includes a [1] in the beginning. `'[1] /Users/.../000017.3587450021.png'`.

It seems that the latest release of https://github.com/lstein/stable-diffusion changed the text output after completion. 
I pushed a fix, the bot now parses the format from `release-1.14.1`, and I added a corresponding remark to the readme install section.

Should work for you now.

**Comment by brian000** [comment]
That fixed it!  Thank you!
