### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by EddieVec** [Djings/slacksd#6]
Running the tool in Windows I am able to get an :eyes: response from the bot in Slack, implying that the bot integration element is working nicely. I then see the console for socket_bot.py showing an attempt to parse the command, followed by an exception as follows:

```DEBUG:SlackSD: process parsed and sanatize prompt: Three hammers
DEBUG:slack_sdk.socket_mode.builtin.client:Message processing completed (type: events_api, envelope_id: 2562ca34-85f1-4601-b23b-c22f9fc937ac)
DEBUG:SlackSD.Puppeteer:run sd process command ['C:\\Users\\username\\source\\slacksd\\execute_prompt']
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\username\source\slacksd\socket_bot.py", line 419, in run
    process = sp.Popen(cmd, stdin=sp.PIPE, stdout=sp.PIPE, stderr=sp.PIPE, text=True)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
```
I'm led to understand this can be caused in Windows by running subprocess without shell=true as per [stackoverflow](https://stackoverflow.com/questions/25651990/oserror-winerror-193-1-is-not-a-valid-win32-application) - adding this to line 419 results in a change, at least, the process fails with an error which is returned to Slack as a reply to the thread:

```
'C:\Users\username\source\slacksd\execute_prompt' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\username\source\slacksd\execute_prompt' is not recognized as an internal or external command,
operable program or batch file.
```

I note that execute_prompt is a shell script, is there no Windows compatability for this tool?

**Comment by Djings** [comment]
I only used it running on a linux up to now. 

However:
Assuming you have https://github.com/lstein/stable-diffusion running locally and can use its cli (called by python scripts/dream.py). It should be relatively easy to get it to work in a Win environment. 

As I gather from your description, the bot itself is running and seeing (👀) your mentions. It then should simply run the cli version of lsteins repo and forward the prompts. Since the shell script for that is a unix specific thing Win complains. You need to create a execute_prompt.bat file that performs 3 things:
1. Change into the stable-diffusion directory
2. activate the ldm conda environment
3. run python scripts/dream.py

All three things can be seen in the included exeute_prompt script. The Windows version should be very similar, try renaming it to execute_prompt.bat and check if you can run it from the terminal manually. I unfortunatly do not have access to a suitable Win machine. If you are wiling to experiment, I can try to assist.

**Comment by EddieVec** [comment]
Yes I was just reflecting on that. 

I've installed InvokeAI using pip and pew rather than conda - Any idea what the pew equivalent of conda activate ldm is?

To run it locally, manually, I use
```
pew workon invokeai
& python scripts\invoke.py
```

Am I right in thinking from execute_prompt, that it initialises the stable_diffusion model for each prompt?

##Also - where is execute_prompt called from please?- scratch this - we set it ourselves >.<

**Comment by Djings** [comment]
Yes, this bot is just a small layer connection slack to a local call to the inference model.

It would be way better to:
* either have the model online from the bot itself
* or at least maintain an open stdin/stdout connection to the interactive cli script in order to keep the model in memory. 

the execute_prompt.bat should just contain any calls you do manually on the command line to launch the cli.
probably something along the lines:
```
cd path/to/your/install
pew workon invokeai
python scripts\invoke.py
```
